# generated by datamodel-codegen:
#   filename:  track.json
#   timestamp: 2026-06-12T05:34:30+00:00

from __future__ import annotations
from enum import IntEnum
from pydantic import Field
from .. import BaseResourceSchema, RelatedResource


class Mode(IntEnum):
    MINOR = 0
    MAJOR = 1


class TrackSchema(BaseResourceSchema):
    name: str = Field(..., description="The name of the track.")
    total_playcount: int | None = Field(
        ..., description="Number of times the song has been played."
    )
    spotify_id: str = Field(..., description="The spotify ID.")
    tags: str = Field(
        ..., description="Tags describing the genres the track belongs to."
    )
    genre: str | None = Field(None, description="The genre.")
    year: int = Field(..., description="The year the track was released.")
    duration_ms: int = Field(..., description="The duration in milliseconds.")
    danceability: float = Field(
        ..., description="An algorithmic estimation of the track danceability."
    )
    mode: Mode = Field(..., description="Major or minor.")
    valence: float = Field(
        ...,
        description="An algorithmic estimation of the track valence. Valence describes musical positivity.",
    )
    artists: list[RelatedResource]
    albums: list[RelatedResource]
