"""
TrackParams for validating the request body.
module: models.schemas.tracks.track_params
generated by datamodel-codegen:
  filename:  track_payload.json
  timestamp: 2026-06-18T13:11:15+00:00
"""

from __future__ import annotations
from pydantic import BaseModel, Field
from .track import Mode


class TrackParams(BaseModel):
    name: str = Field(..., description="The name of the track.")
    total_playcount: int | None = Field(
        None, description="Number of times the song has been played."
    )
    spotify_id: str | None = Field(None, description="The spotify ID.")
    tags: list[str] | None = Field(
        None, description="Tags describing the genres the track belongs to."
    )
    genre: str | None = Field(None, description="The genre.")
    year: int = Field(..., description="The year the track was released.")
    duration_ms: int | None = Field(None, description="The duration in milliseconds.")
    danceability: float | None = Field(
        None, description="An algorithmic estimation of the track danceability."
    )
    mode: Mode | None = Field(None, description="Major or minor.")
    valence: float | None = Field(
        None,
        description="An algorithmic estimation of the track valence. Valence describes musical positivity.",
    )
    artist_ids: list[int] = Field(
        ...,
        description="An array containing the IDs of artists that worked on the track.",
        min_length=1,
    )
    album_ids: list[int] = Field(
        ...,
        description="An array of IDs of albums where the track appears.",
        min_length=1,
    )
