FROM python:3.9-slim

COPY --from=ghcr.io/astral-sh/uv:0.10.5 /uv /uvx /bin/

WORKDIR /app

COPY tracks-api/requirements.txt .
COPY tracks-api/uv.lock .
COPY tracks-api/pyproject.toml .

COPY tracks-api/README.md .
COPY ../models /models

RUN apk update && apk add --no-cache \
    curl

RUN uv sync --frozen --no-dev

COPY tracks-api/ .

CMD ["uv", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "5000"]
