FROM python:3.9-slim

ARG TRACKS_PORT=5010
ENV TRACKS_PORT=${TRACKS_PORT}
ARG ROOT_PATH=""
ENV ROOT_PATH=${ROOT_PATH}

COPY --from=ghcr.io/astral-sh/uv:0.10.5 /uv /uvx /bin/

WORKDIR /app

COPY tracks-api/uv.lock tracks-api/pyproject.toml tracks-api/README.md ./
COPY models /models

RUN apt-get -y update && apt-get -y install curl --no-install-recommends

RUN uv sync --frozen --no-dev

COPY tracks-api/src ./src
COPY tracks-api/static ./static

CMD ["sh", "-c", "if [ -n \"$ROOT_PATH\" ]; \
    then uv run uvicorn src.main:app \
    --host 0.0.0.0 --port $TRACKS_PORT \
    --root-path $ROOT_PATH; \
    else uv run uvicorn src.main:app --host 0.0.0.0 --port $TRACKS_PORT; fi"]
