FROM python:3.9-slim

ARG TRACKS_PORT=5010
ENV TRACKS_PORT=${TRACKS_PORT}

COPY --from=ghcr.io/astral-sh/uv:0.10.5 /uv /uvx /bin/

WORKDIR /app

COPY tracks-api/requirements.txt .
COPY tracks-api/uv.lock .
COPY tracks-api/pyproject.toml .

COPY tracks-api/README.md .
COPY ../models /models

RUN apt-get -y update; apt-get -y install curl

RUN uv sync --frozen --no-dev

COPY tracks-api/ .

CMD ["sh", "-c", "uv run uvicorn src.main:app --host 0.0.0.0 --port $TRACKS_PORT"]
