FROM python:3.12-alpine3.22

COPY --from=ghcr.io/astral-sh/uv:0.10.5 /uv /uvx /bin/

WORKDIR /app

COPY seed/uv.lock seed/pyproject.toml ./
COPY models /models

# Sync dependencies
RUN uv sync --frozen --no-dev

# Copy the src directory
COPY seed/src ./src

# Set PYTHONPATH to include /app
ENV PYTHONPATH=/app

CMD ["/app/.venv/bin/python", "src/main.py"]
