FROM python:3.12-alpine3.22

COPY --from=ghcr.io/astral-sh/uv:0.10.5 /uv /uvx /bin/

WORKDIR /app

COPY auth-service/requirements.txt .
COPY auth-service/uv.lock .
COPY auth-service/pyproject.toml .
COPY ../models /models
COPY auth-service/README.md .

RUN apk update && apk add --no-cache \
    postgresql-dev \
    gcc \
    python3-dev \
    musl-dev \
    libffi-dev \
    openssl-dev \
    libstdc++ \
    curl

RUN uv sync --frozen --no-dev

COPY auth-service/ .

CMD ["uv", "run", "gunicorn", "--bind", "0.0.0.0:5010", "--workers", "2", "src.main:app"]
