FROM python:3.12-alpine3.22

ARG AUTH_PORT=5020
ENV AUTH_PORT=${AUTH_PORT}

COPY --from=ghcr.io/astral-sh/uv:0.10.5 /uv /uvx /bin/

WORKDIR /app

RUN apk add --no-cache curl

COPY auth-service/uv.lock auth-service/pyproject.toml auth-service/README.md ./
COPY models /models

RUN uv sync --frozen --no-dev

COPY auth-service/src ./src
COPY auth-service/static ./static

CMD ["sh", "-c", "/app/.venv/bin/gunicorn --bind 0.0.0.0:$AUTH_PORT --workers 2 src.main:app"]
