# generated by datamodel-codegen:
#   filename:  artist.json
#   timestamp: 2026-06-19T13:29:48+00:00

from __future__ import annotations
from pydantic import Field
from .. import BaseResourceSchema, RelatedResource


class ArtistSchema(BaseResourceSchema):
    name: str = Field(..., description="The name of the artist.")
    tracks: str = Field(
        ..., description="URL to the tracks collection filtered by the artist ID."
    )
    albums: list[RelatedResource] = Field(
        ..., description="The albums the artist has worked on."
    )
