# generated by datamodel-codegen:
#   filename:  base_resource.json
#   timestamp: 2026-05-19T14:58:00+00:00

from __future__ import annotations
from datetime import datetime
from pydantic import BaseModel, Field


class BaseResourceSchema(BaseModel):
    id: int = Field(..., ge=0, description="The ID of the resource")
    href: str = Field(..., description="self-link", title="")
    created_at: datetime
    updated_at: datetime
