# generated by datamodel-codegen:
#   filename:  related_resource.json
#   timestamp: 2026-05-21T07:32:56+00:00

from __future__ import annotations
from pydantic import BaseModel, Field


class RelatedResource(BaseModel):
    id: int = Field(..., ge=1, description="The ID of the resource")
    href: str = Field(..., description="Link to the resource")
