# generated by datamodel-codegen:
#   filename:  album.json
#   timestamp: 2026-06-19T14:10:22+00:00

from __future__ import annotations
from pydantic import Field
from .. import BaseResourceSchema, RelatedResource


class AlbumSchema(BaseResourceSchema):
    name: str = Field(..., description="The album name.")
    tracks: str = Field(
        ..., description="URL to the tracks collection filtered by the album ID."
    )
    artists: list[RelatedResource] = Field(
        ..., description="Artists that worked on the album."
    )
